# Generated by Django 4.1.6 on 2023-04-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
