# Generated by Django 4.1.6 on 2023-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_brand_user_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
