export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST'
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS'
export const PRODUCT_CREATE_FAIL    = 'PRODUCT_CREATE_FAIL'
export const PRODUCT_CREATE_RESET   = 'PRODUCT_CREATE_RESET'

export const PRODUCTS_GET_REQUEST = 'PRODUCTS_GET_REQUEST'
export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS'
export const PRODUCTS_GET_FAIL    = 'PRODUCTS_GET_FAIL'
export const PRODUCTS_GET_RESET   = 'PRODUCTS_GET_RESET'