export const SET_SIDEBAR_STATE_REQUEST = 'SET_SIDEBAR_STATE_REQUEST'
export const SET_SIDEBAR_STATE_SUCCESS = 'SET_SIDEBAR_STATE_SUCCESS'
export const SET_SIDEBAR_STATE_FAIL    = 'SET_SIDEBAR_STATE_FAIL'
export const SET_SIDEBAR_STATE_RESET   = 'SET_SIDEBAR_STATE_RESET'