export const SET_THEME_REQUEST = 'SET_THEME_REQUEST'
export const SET_THEME_SUCCESS = 'SET_THEME_SUCCESS'
export const SET_THEME_FAIL    = 'SET_THEME_FAIL'
export const SET_THEME_RESET   = 'SET_THEME_RESET'